ADDRESS: # net address host:port to run server
    host: localhost
    port: 8080
STORE_INTERVAL: 300 # интервал времени в секундах, по истечении которого текущие показания сервера сохраняются на диск (по умолчанию 300 секунд, значение 0 делает запись синхронной)
FILE_STORAGE_PATH: store.txt # путь до файла, куда сохраняются текущие значения
RESTORE: true # определяет загружать или нет ранее сохранённые значения из указанного файла при старте сервера
DATABASE_DSN: # данные для подключения к базе данных
    host: localhost
    dbname: metrics
    login: metrics
    password: ""
