// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: models/grps/metric.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metric_MetricType int32

const (
	Metric_GAUGE   Metric_MetricType = 0
	Metric_COUNTER Metric_MetricType = 1
)

// Enum value maps for Metric_MetricType.
var (
	Metric_MetricType_name = map[int32]string{
		0: "GAUGE",
		1: "COUNTER",
	}
	Metric_MetricType_value = map[string]int32{
		"GAUGE":   0,
		"COUNTER": 1,
	}
)

func (x Metric_MetricType) Enum() *Metric_MetricType {
	p := new(Metric_MetricType)
	*p = x
	return p
}

func (x Metric_MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Metric_MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_grps_metric_proto_enumTypes[0].Descriptor()
}

func (Metric_MetricType) Type() protoreflect.EnumType {
	return &file_models_grps_metric_proto_enumTypes[0]
}

func (x Metric_MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Metric_MetricType.Descriptor instead.
func (Metric_MetricType) EnumDescriptor() ([]byte, []int) {
	return file_models_grps_metric_proto_rawDescGZIP(), []int{0, 0}
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         // имя метрики//
	MType         Metric_MetricType      `protobuf:"varint,2,opt,name=mType,proto3,enum=protofile.Metric_MetricType" json:"mType,omitempty"` // параметр, принимающий значение gauge или counter
	Delta         int64                  `protobuf:"zigzag64,3,opt,name=delta,proto3" json:"delta,omitempty"`                                // значение метрики в случае передачи counter
	Value         float64                `protobuf:"fixed64,4,opt,name=Value,proto3" json:"Value,omitempty"`                                 // значение метрики в случае передачи gauge
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_models_grps_metric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_models_grps_metric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_models_grps_metric_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Metric) GetMType() Metric_MetricType {
	if x != nil {
		return x.MType
	}
	return Metric_GAUGE
}

func (x *Metric) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type AddMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMetricRequest) Reset() {
	*x = AddMetricRequest{}
	mi := &file_models_grps_metric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMetricRequest) ProtoMessage() {}

func (x *AddMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_grps_metric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMetricRequest.ProtoReflect.Descriptor instead.
func (*AddMetricRequest) Descriptor() ([]byte, []int) {
	return file_models_grps_metric_proto_rawDescGZIP(), []int{1}
}

func (x *AddMetricRequest) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *AddMetricRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type AddMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMetricResponse) Reset() {
	*x = AddMetricResponse{}
	mi := &file_models_grps_metric_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMetricResponse) ProtoMessage() {}

func (x *AddMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_grps_metric_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMetricResponse.ProtoReflect.Descriptor instead.
func (*AddMetricResponse) Descriptor() ([]byte, []int) {
	return file_models_grps_metric_proto_rawDescGZIP(), []int{2}
}

func (x *AddMetricResponse) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

type AddMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*Metric              `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMetricsRequest) Reset() {
	*x = AddMetricsRequest{}
	mi := &file_models_grps_metric_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMetricsRequest) ProtoMessage() {}

func (x *AddMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_models_grps_metric_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMetricsRequest.ProtoReflect.Descriptor instead.
func (*AddMetricsRequest) Descriptor() ([]byte, []int) {
	return file_models_grps_metric_proto_rawDescGZIP(), []int{3}
}

func (x *AddMetricsRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *AddMetricsRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type AddMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMetricsResponse) Reset() {
	*x = AddMetricsResponse{}
	mi := &file_models_grps_metric_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMetricsResponse) ProtoMessage() {}

func (x *AddMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_models_grps_metric_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMetricsResponse.ProtoReflect.Descriptor instead.
func (*AddMetricsResponse) Descriptor() ([]byte, []int) {
	return file_models_grps_metric_proto_rawDescGZIP(), []int{4}
}

func (x *AddMetricsResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_models_grps_metric_proto protoreflect.FileDescriptor

const file_models_grps_metric_proto_rawDesc = "" +
	"\n" +
	"\x18models/grps/metric.proto\x12\tprotofile\"\x9e\x01\n" +
	"\x06Metric\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x05mType\x18\x02 \x01(\x0e2\x1c.protofile.Metric.MetricTypeR\x05mType\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\x12R\x05delta\x12\x14\n" +
	"\x05Value\x18\x04 \x01(\x01R\x05Value\"$\n" +
	"\n" +
	"MetricType\x12\t\n" +
	"\x05GAUGE\x10\x00\x12\v\n" +
	"\aCOUNTER\x10\x01\"Q\n" +
	"\x10AddMetricRequest\x12)\n" +
	"\x06metric\x18\x01 \x01(\v2\x11.protofile.MetricR\x06metric\x12\x12\n" +
	"\x04Body\x18\x02 \x01(\fR\x04Body\">\n" +
	"\x11AddMetricResponse\x12)\n" +
	"\x06metric\x18\x01 \x01(\v2\x11.protofile.MetricR\x06metric\"T\n" +
	"\x11AddMetricsRequest\x12+\n" +
	"\ametrics\x18\x01 \x03(\v2\x11.protofile.MetricR\ametrics\x12\x12\n" +
	"\x04Body\x18\x02 \x01(\fR\x04Body\"*\n" +
	"\x12AddMetricsResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count2\xa0\x01\n" +
	"\aMetrics\x12F\n" +
	"\tAddMetric\x12\x1b.protofile.AddMetricRequest\x1a\x1c.protofile.AddMetricResponse\x12M\n" +
	"\x0eAddMetricBatch\x12\x1c.protofile.AddMetricsRequest\x1a\x1d.protofile.AddMetricsResponseB\x0eZ\fmodels/protob\x06proto3"

var (
	file_models_grps_metric_proto_rawDescOnce sync.Once
	file_models_grps_metric_proto_rawDescData []byte
)

func file_models_grps_metric_proto_rawDescGZIP() []byte {
	file_models_grps_metric_proto_rawDescOnce.Do(func() {
		file_models_grps_metric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_grps_metric_proto_rawDesc), len(file_models_grps_metric_proto_rawDesc)))
	})
	return file_models_grps_metric_proto_rawDescData
}

var file_models_grps_metric_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_models_grps_metric_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_models_grps_metric_proto_goTypes = []any{
	(Metric_MetricType)(0),     // 0: protofile.Metric.MetricType
	(*Metric)(nil),             // 1: protofile.Metric
	(*AddMetricRequest)(nil),   // 2: protofile.AddMetricRequest
	(*AddMetricResponse)(nil),  // 3: protofile.AddMetricResponse
	(*AddMetricsRequest)(nil),  // 4: protofile.AddMetricsRequest
	(*AddMetricsResponse)(nil), // 5: protofile.AddMetricsResponse
}
var file_models_grps_metric_proto_depIdxs = []int32{
	0, // 0: protofile.Metric.mType:type_name -> protofile.Metric.MetricType
	1, // 1: protofile.AddMetricRequest.metric:type_name -> protofile.Metric
	1, // 2: protofile.AddMetricResponse.metric:type_name -> protofile.Metric
	1, // 3: protofile.AddMetricsRequest.metrics:type_name -> protofile.Metric
	2, // 4: protofile.Metrics.AddMetric:input_type -> protofile.AddMetricRequest
	4, // 5: protofile.Metrics.AddMetricBatch:input_type -> protofile.AddMetricsRequest
	3, // 6: protofile.Metrics.AddMetric:output_type -> protofile.AddMetricResponse
	5, // 7: protofile.Metrics.AddMetricBatch:output_type -> protofile.AddMetricsResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_models_grps_metric_proto_init() }
func file_models_grps_metric_proto_init() {
	if File_models_grps_metric_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_grps_metric_proto_rawDesc), len(file_models_grps_metric_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_models_grps_metric_proto_goTypes,
		DependencyIndexes: file_models_grps_metric_proto_depIdxs,
		EnumInfos:         file_models_grps_metric_proto_enumTypes,
		MessageInfos:      file_models_grps_metric_proto_msgTypes,
	}.Build()
	File_models_grps_metric_proto = out.File
	file_models_grps_metric_proto_goTypes = nil
	file_models_grps_metric_proto_depIdxs = nil
}
