// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/s-turchinskiy/metrics/internal/server/repository (interfaces: Repository)

// Package mocksrepository is a generated GoMock package.
package mocksrepository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	models "github.com/s-turchinskiy/metrics/internal/server/models"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CountCounters mocks base method.
func (m *MockRepository) CountCounters(arg0 context.Context) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCounters", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// CountCounters indicates an expected call of CountCounters.
func (mr *MockRepositoryMockRecorder) CountCounters(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCounters", reflect.TypeOf((*MockRepository)(nil).CountCounters), arg0)
}

// CountGauges mocks base method.
func (m *MockRepository) CountGauges(arg0 context.Context) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountGauges", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// CountGauges indicates an expected call of CountGauges.
func (mr *MockRepositoryMockRecorder) CountGauges(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountGauges", reflect.TypeOf((*MockRepository)(nil).CountGauges), arg0)
}

// GetAllCounters mocks base method.
func (m *MockRepository) GetAllCounters(arg0 context.Context) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCounters", arg0)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCounters indicates an expected call of GetAllCounters.
func (mr *MockRepositoryMockRecorder) GetAllCounters(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCounters", reflect.TypeOf((*MockRepository)(nil).GetAllCounters), arg0)
}

// GetAllGauges mocks base method.
func (m *MockRepository) GetAllGauges(arg0 context.Context) (map[string]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllGauges", arg0)
	ret0, _ := ret[0].(map[string]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllGauges indicates an expected call of GetAllGauges.
func (mr *MockRepositoryMockRecorder) GetAllGauges(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllGauges", reflect.TypeOf((*MockRepository)(nil).GetAllGauges), arg0)
}

// GetCounter mocks base method.
func (m *MockRepository) GetCounter(arg0 context.Context, arg1 string) (int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockRepositoryMockRecorder) GetCounter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockRepository)(nil).GetCounter), arg0, arg1)
}

// GetGauge mocks base method.
func (m *MockRepository) GetGauge(arg0 context.Context, arg1 string) (float64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGauge", arg0, arg1)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetGauge indicates an expected call of GetGauge.
func (mr *MockRepositoryMockRecorder) GetGauge(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGauge", reflect.TypeOf((*MockRepository)(nil).GetGauge), arg0, arg1)
}

// Ping mocks base method.
func (m *MockRepository) Ping(arg0 context.Context) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ping indicates an expected call of Ping.
func (mr *MockRepositoryMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRepository)(nil).Ping), arg0)
}

// ReloadAllCounters mocks base method.
func (m *MockRepository) ReloadAllCounters(arg0 context.Context, arg1 map[string]int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReloadAllCounters", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReloadAllCounters indicates an expected call of ReloadAllCounters.
func (mr *MockRepositoryMockRecorder) ReloadAllCounters(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReloadAllCounters", reflect.TypeOf((*MockRepository)(nil).ReloadAllCounters), arg0, arg1)
}

// ReloadAllGauges mocks base method.
func (m *MockRepository) ReloadAllGauges(arg0 context.Context, arg1 map[string]float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReloadAllGauges", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReloadAllGauges indicates an expected call of ReloadAllGauges.
func (mr *MockRepositoryMockRecorder) ReloadAllGauges(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReloadAllGauges", reflect.TypeOf((*MockRepository)(nil).ReloadAllGauges), arg0, arg1)
}

// ReloadAllMetrics mocks base method.
func (m *MockRepository) ReloadAllMetrics(arg0 context.Context, arg1 []models.StorageMetrics) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReloadAllMetrics", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReloadAllMetrics indicates an expected call of ReloadAllMetrics.
func (mr *MockRepositoryMockRecorder) ReloadAllMetrics(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReloadAllMetrics", reflect.TypeOf((*MockRepository)(nil).ReloadAllMetrics), arg0, arg1)
}

// UpdateCounter mocks base method.
func (m *MockRepository) UpdateCounter(arg0 context.Context, arg1 string, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCounter", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCounter indicates an expected call of UpdateCounter.
func (mr *MockRepositoryMockRecorder) UpdateCounter(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCounter", reflect.TypeOf((*MockRepository)(nil).UpdateCounter), arg0, arg1, arg2)
}

// UpdateGauge mocks base method.
func (m *MockRepository) UpdateGauge(arg0 context.Context, arg1 string, arg2 float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGauge", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateGauge indicates an expected call of UpdateGauge.
func (mr *MockRepositoryMockRecorder) UpdateGauge(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGauge", reflect.TypeOf((*MockRepository)(nil).UpdateGauge), arg0, arg1, arg2)
}
