package main

import (
	"github.com/s-turchinskiy/metrics/internal/common/codegeneration"
	"log"
	"os"
)

//go generate ./internal/staticlint/standard/generate/generate_standard.go //дергать так

const dir = "/home/stanislav/go/pkg/mod/golang.org/x/tools@v0.0.0-20190611222205-d73e1c7e250b/go/analysis/passes"

const templateStr = `
// Code generated by go generate; DO NOT EDIT.
// This file was generated by generate_standard.go

//Package standard Стандартные анализаторы go
package standard

import (
"golang.org/x/tools/go/analysis"

{{range .}}"golang.org/x/tools/go/analysis/passes/{{.}}"
{{end}}

)

func GetStandardAnalyzers() []*analysis.Analyzer {
	var analyzers []*analysis.Analyzer

	analyzers = append(analyzers,
	{{range .}}{{.}}.Analyzer,
	{{end}}
	)
		return analyzers
}`

//go:generate go run generate_standard.go
func main() {

	files, err := os.ReadDir(dir)
	if err != nil {
		log.Fatal(err)
	}

	data := make([]string, 0, 50)

	for _, file := range files {
		if file.IsDir() && file.Name() != "internal" {
			data = append(data, file.Name())
		}
	}

	codegeneration.Codogeneration(data, templateStr, "../standard.go")

}
